version: '0.0.1+{build}'
configuration: Release
image: Visual Studio 2017

clone_depth: 1

nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'

before_build:
- ps: dotnet restore -s "https://api.nuget.org/v3/index.json" --verbosity m

build_script:
- dotnet build -c %CONFIGURATION%

after_build:
- dotnet pack -c %CONFIGURATION% --no-build -o artifacts

test_script:
- dotnet test -c %CONFIGURATION%

artifacts:
 - path: '**\*.nupkg'

deploy:
  - provider: NuGet
    api_key:
      secure: qv8neZddxXHFevH4lLUAfjVud3fhjTR3J022rlTsgIPqkASxZ/jHjB38nkUJYFGT
    skip_symbols: false
    artifact: /.*\.nupkg/
    on:
      branch: master
      appveyor_repo_tag: true

  - provider: GitHub
    artifact: /.*\.nupkg/           # upload all NuGet packages to release assets
    draft: false
    prerelease: false
    auth_token:
      secure: ciT780F14J207Y8r947Il6TBZQG8xJfvYqOZaU+EsBhDzzzN/sdtETKju59U6hbs
    on:
      branch: master                # release from master branch only
      appveyor_repo_tag: true