trigger:
- master
- refs/tags/*
- feature/*

pr:
  autoCancel: true
  branches:
    include:
      - master
  paths:
    include:
    - src/*
    - tests/*

pool:
  vmImage: 'windows-2019'

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    useGlobalJson: true
- script: dotnet --info
  displayName: Dump Info
- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'run'
    arguments: '--project ./build/_build.csproj -target CI'
- task: PublishTestResults@2
  inputs:
   testResultsFormat: 'VSTest'
   testResultsFiles: '*.trx'
   searchFolder: 'artifacts/tests'
  displayName: 'Publish Test results'
- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: cobertura
    summaryFileLocation: artifacts/tests/coverage.cobertura.xml
    reportDirectory: artifacts/tests/Reports
    failIfCoverageEmpty: true
  displayName: 'Publish Code Coverage'
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: 'artifacts/nuget'
    artifactName: 'Nuget'
  displayName: 'Publish Packages'