FROM microsoft/dotnet:2.2-sdk-alpine AS build
WORKDIR /app

# copy csproj and restore as distinct layers
COPY . .
RUN dotnet restore
RUN dotnet test -c Release
WORKDIR ./test/Beffyman.UdpServer.Demo
RUN dotnet publish Beffyman.UdpServer.Demo.csproj -c Release -o bin/publish

FROM microsoft/dotnet:2.2-runtime-alpine AS runtime
WORKDIR /app
COPY --from=build /app/test/Beffyman.UdpServer.Demo/bin/publish ./

EXPOSE 6002:6002/udp
ENTRYPOINT ["dotnet", "Beffyman.UdpServer.Demo.dll"]